"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useState } from "react";

type Question = { id: string; type: "mcq" | "short" | "explain"; prompt: string; options: string[] | null; isReview: boolean };
type QuizResponse = { questions: Question[] };
type Result = { score: number; passed: boolean; answers: { prompt: string; response: string; score: number; feedback: string; modelAnswer: string; missedConcept: string | null }[] };

export function QuizPage() {
  const params = useParams<{ id: string; idx: string }>(); const queryClient = useQueryClient();
  const [currentIndex, setCurrentIndex] = useState(0); const [responses, setResponses] = useState<Record<string, string>>({}); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState("");
  const quiz = useQuery<QuizResponse>({ queryKey: ["quiz", params.id, params.idx], queryFn: async () => { const course = await fetch(`/api/courses/${params.id}`).then((response) => response.json()); const chapter = course.chapters.find((item: { idx: number }) => item.idx === Number(params.idx)); return fetch(`/api/chapters/${chapter.id}/quiz`).then((response) => { if (!response.ok) throw new Error("Could not load QnA"); return response.json(); }); } });
  const questions = quiz.data?.questions ?? []; const question = questions[currentIndex];
  async function submit() { if (!questions.every((item) => responses[item.id]?.trim())) { setError("Answer each question before submitting."); return; } setError(""); const course = await fetch(`/api/courses/${params.id}`).then((response) => response.json()); const chapter = course.chapters.find((item: { idx: number }) => item.idx === Number(params.idx)); const response = await fetch(`/api/chapters/${chapter.id}/attempts`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ answers: questions.map((item) => ({ questionId: item.id, response: responses[item.id] })) }) }); const body = await response.json(); if (!response.ok) { setError(body?.error?.message ?? "Could not submit the QnA."); return; } setResult(body); }
  if (quiz.isLoading) return <main className="reading-shell ui text-sm text-[var(--muted)]">Preparing your QnA…</main>;
  if (quiz.isError || !question) return <main className="reading-shell ui text-sm text-[var(--accent-dark)]">Could not load this QnA.</main>;
  if (result) { const nextIdx = Number(params.idx) + 1; const nextHref = result.passed ? `/course/${params.id}/ch/${nextIdx}` : `/course/${params.id}/ch/${params.idx}`; return <main className="reading-shell"><Link href={`/course/${params.id}`} className="eyebrow no-underline hover:text-[var(--accent-dark)]">Mastery Tutor</Link><h1 className="display mt-16 text-6xl leading-none">{result.passed ? "Chapter complete" : "Keep going"}</h1><p className="display mt-5 text-7xl text-[var(--accent)]">{Math.round(result.score * 100)}%</p><p className="mt-3 text-xl text-[var(--muted)]">{result.passed ? "You understand the core ideas." : "Review the feedback, then try a fresh QnA."}</p><div className="mt-10 divide-y divide-[var(--line)] border-y border-[var(--line)]">{result.answers.map((answer, index) => <div className="py-5" key={`${answer.prompt}-${index}`}><p className="text-xl">{index + 1}. {answer.prompt}</p><p className={`ui mt-2 text-sm ${answer.score >= 0.8 ? "text-[var(--success)]" : "text-[var(--accent-dark)]"}`}>{answer.feedback}</p><p className="mt-2 text-sm text-[var(--muted)]">Model answer: {answer.modelAnswer}</p></div>)}</div><Link href={result.passed ? nextHref : `/course/${params.id}/ch/${params.idx}/quiz`} onClick={() => { if (!result.passed) { setResult(null); setResponses({}); setCurrentIndex(0); queryClient.invalidateQueries({ queryKey: ["quiz", params.id, params.idx] }); } }} className="button-primary ui mt-10 w-full">{result.passed ? "Continue" : "Try again"}</Link><Link href={`/course/${params.id}/ch/${params.idx}`} className="ui mt-4 block text-center text-xs text-[var(--muted)] hover:text-[var(--ink)]">Review chapter</Link></main>; }
  return <main className="reading-shell"><header className="border-b border-[var(--line)] pb-5"><div className="flex items-center justify-between gap-4"><Link href={`/course/${params.id}/ch/${params.idx}`} className="eyebrow no-underline hover:text-[var(--accent-dark)]">Back to chapter</Link><span className="ui text-xs text-[var(--muted)]">{currentIndex + 1} / {questions.length}</span></div><div className="mt-4 h-1 bg-[var(--line)]"><div className="h-1 bg-[var(--accent)]" style={{ width: `${((currentIndex + 1) / questions.length) * 100}%` }} /></div></header><p className="eyebrow mt-16">{question.isReview ? "Review question" : "Check your understanding"}</p><h1 className="display mt-4 text-5xl leading-none">{question.prompt}</h1><div className="mt-10">{question.type === "mcq" && question.options ? <div className="space-y-3">{question.options.map((option, index) => <label className="flex cursor-pointer items-center gap-3 border border-[var(--line)] px-4 py-4 transition-colors hover:border-[var(--accent)]" key={option}><input type="radio" name={question.id} checked={responses[question.id] === option} onChange={() => setResponses({ ...responses, [question.id]: option })} />{String.fromCharCode(65 + index)}. {option}</label>)}</div> : <textarea rows={7} value={responses[question.id] ?? ""} onChange={(event) => setResponses({ ...responses, [question.id]: event.target.value })} className="field" placeholder="Explain in your own words…" />}</div>{error ? <p className="ui mt-4 text-sm text-[var(--accent-dark)]" role="alert">{error}</p> : null}<button type="button" onClick={() => currentIndex + 1 < questions.length ? setCurrentIndex(currentIndex + 1) : submit()} className="button-primary ui mt-8 w-full">{currentIndex + 1 < questions.length ? "Next question" : "Submit answers"}</button></main>;
}
